apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: dev
type: Opaque
stringData:
  RABBITMQ_HOST: rabbitmq
  MP3_QUEUE: mp3
  GMAIL_ADDRESS: your-gmail@gmail.com
  GMAIL_PASSWORD: your-gmail-app-password
