apiVersion: v1
kind: Secret
metadata:
  name: gateway-service-secret
  namespace: dev
type: Opaque
stringData:
  MONGO_VIDEO_URI: mongodb://root:rootpassword@mongodb:27017/videos?authSource=admin
  MONGO_MP3_URI: mongodb://root:rootpassword@mongodb:27017/mp3s?authSource=admin
  RABBITMQ_HOST: rabbitmq
  VIDEO_QUEUE: video
  MP3_QUEUE: mp3
  AUTH_SVC_ADDRESS: auth-service:5000
